### ISSUE TITLE
Invalid claim search makes API crash

### ISSUE THREAD

**Issue by Pigges** [Pigges/lbry-stats#1]
When entering an invalid/incorrect claim, the API crashes because the sd_hash could not be found.
Overall, there should be more error handling.

Traceback
```js
if (!query.query) return {"message": "expected query"};

let resolve = await (await API('resolve', {urls: query.query})).json();
     resolve = Object.values(resolve.result)[0];
     let peer_list = await pagination('peer_list', {
         "blob_hash": resolve.value.source.sd_hash,
                          ^
 TypeError: undefined is not an object (evaluating 'resolve.value.source')
       at /var/www/lbry-stats/src/utils/api.js:51:21
     if (!query.query) return {"message": "expected query"};

     let resolve = await (await API('resolve', {urls: query.query})).json();
     resolve = Object.values(resolve.result)[0];
     let peer_list = await pagination('peer_list', {
         "blob_hash": resolve.value.source.sd_hash,
                          ^
 TypeError: undefined is not an object (evaluating 'resolve.value.source')
       at /var/www/lbry-stats/src/utils/api.js:51:21
```

**Comment by Pigges** [comment]
Closing as irrelevant.
